### PR TITLE
UI ios 26 fixes after UI review part four

### LINKED ISSUE #5108: UI fixes after migration to iOS 26
# Critical

## My Places

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [ ] Hide Search bar in Edit mode for Favorites
- [ ] Use sf symbol `pencil` for edit icon.

# Other
## Purchases

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [ ] **Learn more** text 
- [ ] Icon color for Restore button in NavBar (if it use raster icon ask @dmpr0 for vector)
- - [ ] Button size 

## CarPlay

It seems we need to use buttons without background on iOS 26 CarPlay

## Maps & Resources

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [ ] Download Map dialog is below Search bar

# My Places

### PR DESCRIPTION
**Pull request by DmitrySvetlichny**

### CODE REVIEW

File: Sources/Controllers/Base/OABaseNavbarViewController.m [hunk 1]
```diff
@@ -147,9 +146,8 @@ - (void)viewWillDisappear:(BOOL)animated
 
     if (![self.navigationController isNavigationBarHidden])
     {
-        //hide root navbar if open screen without navbar
-        if (![self.navigationController.viewControllers.lastObject isNavbarVisible])
-            [self.navigationController setNavigationBarHidden:YES animated:YES];
+        if ([self shouldResetNavbarForTransition])
```
Comment (tigrim) [inline Sources/Controllers/Base/OABaseNavbarViewController.m]: shouldHideNavbarForTransition

File: Sources/Controllers/Base/OABaseNavbarViewController.m [hunk 2]
```diff
@@ -108,8 +108,7 @@ - (void)viewWillAppear:(BOOL)animated
     }
 
     self.navigationController.navigationBar.prefersLargeTitles = YES;
-    if ([self.navigationController isNavigationBarHidden] && [self isNavbarVisible])
```
Comment (tigrim) [inline Sources/Controllers/Base/OABaseNavbarViewController.m:111]: ?

File: Sources/Controllers/Base/OABaseNavbarViewController.m [hunk 3]
```diff
@@ -520,6 +565,10 @@ - (void)setupNavbarButtons
             {
                 leftNavbarButtonCustomIcon = [UIImage templateImageNamed:ACImageNameIcNavbarChevron];
                 freeSpaceForNavbarButton = 30.;
+                leftButton.contentHorizontalAlignment = UIControlContentHorizontalAlignmentCenter;
+                UIButtonConfiguration *configuration = leftButton.configuration ?: [UIButtonConfiguration plainButtonConfiguration];
```
Comment (tigrim) [inline Sources/Controllers/Base/OABaseNavbarViewController.m]: ?

**Review by tigrim — APPROVED** [review]
