### PR TITLE
next turn widget red background fixed

### LINKED ISSUE #5231: CarPlay: Next turn widget background unexpectedly turns red during navigation
### How to reproduce
* Connect to CarPlay
* Start Navigation

### Actual result
<table style="width:100%">
  <tr>
    <td> </td>
  </tr>
</table>   

* The **Next Turn Widget** background has turned red.

### Expected result
* The application should use the default **iOS Theme**.

**Environment**
OsmAnd Version: 5345
Android/iOS version: 26 Beta 4
Device model: iPhone 16 Pro Max

### PR DESCRIPTION
**Pull request by Vladyslav-lys**

### CODE REVIEW

File: Sources/CarPlay/OACarPlayDashboardInterfaceController.mm [hunk 1]
```diff
@@ -40,12 +40,15 @@
...
-#define unitsFt OALocalizedString(@"foot")
-#define unitsNm OALocalizedString(@"nm")
+static NSString * const kUnitsKm = OALocalizedString(@"km");
+static NSString * const kUnitsM = OALocalizedString(@"m");
+static NSString * const kUnitsMi = OALocalizedString(@"mile");
+static NSString * const kUnitsYd = OALocalizedString(@"yard");
+static NSString * const kUnitsFt = OALocalizedString(@"foot");
+static NSString * const kUnitsNm = OALocalizedString(@"nm");
+
+static UIColor * const kLightColor = [UIColor colorWithRed:0.976 green:0.976 blue:0.984 alpha:1.0];
```
Comment (tigrim) [inline Sources/CarPlay/OACarPlayDashboardInterfaceController.mm]: Use colors from the asset catalog. Align with the designer

File: Sources/CarPlay/OACarPlayDashboardInterfaceController.mm [hunk 2]
```diff
@@ -828,6 +831,11 @@ - (void)onLocationUpdate
                 @"turnImminent": turnType ? @(turnImminent) : @(-1),
                 @"deviatedFromRoute": turnType ? @(deviatedFromRoute) : @(NO),
             };
+            if (@available(iOS 15.4, *))
+            {
+                BOOL isDarkStyle = self.interfaceController.carTraitCollection.userInterfaceStyle == UIUserInterfaceStyleDark;
```
Comment (tigrim) [inline Sources/CarPlay/OACarPlayDashboardInterfaceController.mm]: What’s wrong with guidanceBackgroundColor? Or does maneuver.cardBackgroundColor use a red color?

File: Sources/CarPlay/OACarPlayDashboardInterfaceController.mm [hunk 3]
```diff
@@ -1085,7 +1083,7 @@ - (void)onUpdateMapTemplateStyle
     UIUserInterfaceStyle style = self.interfaceController.carTraitCollection.userInterfaceStyle;
     BOOL isDarkStyle = style == UIUserInterfaceStyleDark;
     NSLog(@"onUpdateMapTemplateStyle: %d (%@)", int(style), isDarkStyle ? @"dark" : @"light");
-    _mapTemplate.guidanceBackgroundColor = isDarkStyle ? _darkGuidanceBackgroundColor : _lightGuidanceBackgroundColor;
+    _mapTemplate.guidanceBackgroundColor = [UIColor colorNamed:ACColorNameCarPlayTurnPreviewBackground];
```
Comment (tigrim) [inline Sources/CarPlay/OACarPlayDashboardInterfaceController.mm]: It’s the wrong approach

**Review by tigrim — APPROVED** [review]
