### PR TITLE
Align hillshade fix black segments

### LINKED ISSUE #5105: Align iOS hillshade functionality with Android
### Description
Currently, Android properly disables vertex hillshades when 3D is disabled or terrain raster hillshades are enabled, improving performance and battery life. iOS lacks this optimization.
So it is proposed to implement consistent terrain hillshades behavior across iOS and Android platforms. 

### ToDo 
- [ ] disable vertex hillshades when 3D is off (should match Android behavior of disabling hillshading in elevation config
- [x] disable vertex hillshade when terrain raster hillshade is on
- [x] add possibility to switch on/off raster hillshades (slopes). Currently it is only possible to set visibility to 0

## Terrain menu, Configure Map

<table style="width:100%">
  <tr>
    <th>Terrain</th>
    <th>Visualization Menu</th>
    <th>Terrain shadowsі</th>
  </tr>
  <tr>
    <td> </td>
    <td> </td>
    <td> </td>
  </tr>
</table>  

**Main group**
- [x] Rename **Color scheme** to **Visualization**
- [x] Add new variant – **Terrain shadows**
- - [x] Description – `Real-time dynamic shading for 3D terrain. Highlights landscape geometry with minimal performance impact.`
- [x] When selected enable vertex hillshades

**Appearance**
- [x] Hide **Zoom levels**, cause it doesn't apply for this type
- [x] Visibility available for this type

**3D Relief**
By default, 3D relief is available only to OsmAnd Pro subscribers. However, with this visualization type, it will be enabled for all users without the option to disable it

- [x] Enable 3D relief automatically whenever **Terrain shadows** is selected, as the feature requires it to function
- [x] Remove the toggle switch and replace it with the text **On**
- [x] Keep Vertical exaggeration available only for OsmAnd Pro subscribers. In other cases it hidden when 3D Relief is Off.
- - [x] Add Pro button next to it
- [x] Add a footer description – `3D Relief is automatically enabled, as it is required to render Terrain shadows.`
- - [x] Ensure this footer is visible only when **Visualization** is set to **Terrain shadows**

### PR DESCRIPTION
**Pull request by Vladyslav-lys**

### CODE REVIEW

File: Sources/Controllers/Map/OAMapViewController.mm [hunk 1]
```diff
@@ -2804,9 +2804,12 @@ - (void)remove3DObjectColor:(OsmAnd::LatLon)latLon
 - (void) updateElevationConfiguration
 {
     OASRTMPlugin *plugin = (OASRTMPlugin *) [OAPluginsHelper getEnabledPlugin:OASRTMPlugin.class];
-    BOOL disableVertexHillshade = plugin && [plugin isTerrainLayerEnabled] && [plugin isHillshadeMode];
     OsmAnd::ElevationConfiguration elevationConfiguration;
-    if (disableVertexHillshade)
+    if (plugin && [plugin isTerrainLayerEnabled] && [plugin isTerrainShadowsMode])
```
Comment (tigrim) [inline Sources/Controllers/Map/OAMapViewController.mm:2808]: Did you lose any logic? For example, when `plugin && [plugin isTerrainLayerEnabled]` is true, it should NOT call:

```
elevationConfiguration.setSlopeAlgorithm(OsmAnd::ElevationConfiguration::SlopeAlgorithm::None);
elevationConfiguration.setVisualizationStyle(OsmAnd::ElevationConfiguration::VisualizationStyle::None);
```

**Review by tigrim — APPROVED** [review]
