### PR TITLE
Delete route line color crush fix

### LINKED ISSUE #5145: Fix Crashes 5.3 - iOS
> Android https://github.com/osmandapp/OsmAnd/issues/24308
> Backend https://github.com/osmandapp/OsmAnd/issues/24400

________

**App version (build)** - **Notes** / - Stacktrace
-------------------------- 

🔴 High Priority (planned to fix first)

- [x] **5.3.0 (5320)** - **UIKitCore: _UIGraphicsBeginImageContextWithOptions + 568**
xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=BnSKhynbvHIcWWN4dpuXsR&bundleId=net.osmand.maps

- [x] **5.3.0 (5320)** -  **OsmAnd Maps: +[OAPublicTransportShieldCell generateTitlesForRoute:] + 652**
  xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=DjF66GGKyTUN7IVqBWTaht&bundleId=net.osmand.maps

- [x] **5.3.0 (5320)** -  **OsmAnd Maps: -[OABaseDeleteFilesCommand publishProgress:] + 236**
 xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=Dqnxe-cTchkeNk7DF5R03q&bundleId=net.osmand.maps

- [x] **5.3.0 (5328)** -  **OsmAnd::MapMarkersCollection_P::removeMarker(std::__1::shared_ptr<OsmAnd::MapMarker> const&) (in OsmAnd Maps) + 68 + 16579128**

- [x] **5.3.0 (5327)** -  ** OAOverlayMapLayer.mm  onOverlayLayerAlphaChanged**
- [x] **5.3.0 (5327)** -  **onVerticalExaggerationScaleChanged**

- [x] **5.3.0 (5331)** -  **OsmAnd Maps: QHash<int, std::__1::shared_ptr<OsmAnd::MapMarker>>::remove(int const&) + 176**
 xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=Du4KIir_BXbFt_8c-2z3wV&bundleId=net.osmand.maps

- [x] **5.3.0 (5331)** -  **OsmAnd Maps: QWriteLocker::relock() + 8**
 xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=BwPCbjwEEZGpoiSUyDRu8p&bundleId=net.osmand.maps

- [ ] **5.3.0 (5337)** -  **UIKitCore: 0x19102a000 + 23360492**
  xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=B4ymyCnrz7t3D7pT1oMb9u&bundleId=net.osmand.maps

🟡 Next in Queue (planned for later)

- [ ] **5.3.0 (5320)** -  **OsmAnd Maps: -[OASearchResultMatcher publish:] + 524**
  xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=b-KuWVmRU5Dn9SpqNXBwx&bundleId=net.osmand.maps

### PR DESCRIPTION
**Pull request by Vladyslav-lys**

### CODE REVIEW

File: Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m [hunk 1]
```diff
@@ -338,20 +338,18 @@ - (void)removeColor:(NSIndexPath *)indexPath
...
         [collectionView deleteItemsAtIndexPaths:@[indexPath]];
         
         if (indexPath == weakSelf.selectedIndexPath)
-        {
             [weakSelf setSelectedIndexPath:[NSIndexPath indexPathForRow:0 inSection:0]];
-            [collectionView reloadItemsAtIndexPaths:@[weakSelf.selectedIndexPath]];
-        }
         else if (indexPath.row < weakSelf.selectedIndexPath.row)
-        {
             [weakSelf setSelectedIndexPath:[NSIndexPath indexPathForRow:weakSelf.selectedIndexPath.row - 1 inSection:weakSelf.selectedIndexPath.section]];
```
Comment (tigrim) [inline Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m:349]: previousSelectedIndexPath ?

**Review by tigrim — APPROVED** [review]
