### PR TITLE
Speedometer fix

### LINKED ISSUE #5285: Common speedometer defects: speedometer drift, incorrect speed display
### Description

> Previous
> 1. [Speedometer widget](https://osmand.net/docs/user/navigation/car-play/#speedometer)
> 2. [speed-limit](https://osmand.net/docs/user/navigation/guidance/voice-navigation/#speed-limit)
> 3. [speedometer info widget](https://osmand.net/docs/user/widgets/info-widgets#speedometer)

Several UI issues are observed during navigation and interaction with the interface in Map mode: 
1. Incorrect vertical positioning of the compass when changing the color scheme
2. Misalignment of the speedometer widget when interacting with the context menu
3. The display of speed with fractional values, which does not meet readability standards

### Steps to reproduce

1. Start the navigation simulation in a country where it is currently nighttime > Wait for the Map mode to change automatically
2. Start the navigation simulator > Select any POI on the map > Open the context menu fully > Tap the geolocation button (to center the map) > Close (collapse) the POI's context menu
3. Start the navigation simulation from `48.15143, 14.03734` to `48.15232, 14.04044` > Monitor the speed reading in the speedometer widget

### Actual result

1. When switching to night mode, the speedometer icon “drops” down, covering other elements or moving outside its standard position
2. After hiding the context menu, the speedometer widget moves upward and hovers over the “Configure map” and search buttons, instead of returning to the lower-left corner
3. The widget displays fractional numbers (e.g., 14.9 km/h), which creates visual clutter

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>1</th>
    <th>2</th>
    <th>3</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/7e23dd44-dfeb-4e07-9848-e24cfe92d59a"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/4cb14102-1619-4db5-897c-d0fee1969806"  width="300" height="auto"/> </td>
    <td><video source src="https://github.com/user-attachments/assets/0f015e65-da26-457c-b651-3b61212eaf4c"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details> 

### Expected result

- [ ] 1. The speedometer should remain fixed in the lower-left corner regardless of the theme (Day/Night)
- [ ] 2. After closing the context menu, the speedometer widget should smoothly return to its default position at the bottom of the screen without covering the control buttons
- [ ] 3. The speed readings on the speedometer must be whole numbers (rounded according to standard rules) to allow the driver to read them quickly

### Your Environment
OsmAnd Version: OsmAnd Maps 5356, released 03.04.26
Android/iOS version: 26.5
Device model: iPhone 15

### PR DESCRIPTION
**Pull request by DmitrySvetlichny**

### CODE REVIEW

File: Sources/Views/SpeedometerView/SpeedometerView.swift [hunk 1]
```diff
@@ -68,7 +68,8 @@ final class SpeedometerView: OATextInfoWidget {
     
     @discardableResult
     override func updateInfo() -> Bool {
-        guard settings.showSpeedometer.get() else {
+        let isContextMenuVisible = !isPreview && carPlayConfig == nil && OARootViewController.instance().mapPanel.isContextMenuVisible()
```
Comment (tigrim) [inline Sources/Views/SpeedometerView/SpeedometerView.swift]: move separated var```
private var shouldShowSpeedometer: Bool {
}
```

File: Sources/Views/SpeedometerView/SpeedometerView.swift [hunk 2]
```diff
@@ -55,6 +55,10 @@ final class SpeedometerView: OATextInfoWidget {
         return drivingRegion == EOADrivingRegion.DR_US || drivingRegion == EOADrivingRegion.DR_CANADA
     }
     
+    private var shouldShowSpeedometer: Bool {
```
Comment (tigrim) [inline Sources/Views/SpeedometerView/SpeedometerView.swift:58]:
```
private var shouldShowSpeedometer: Bool {
    guard settings.showSpeedometer.get() else { return false }

    if isPreview || carPlayConfig != nil {
        return true
    }

    return !OARootViewController.instance().mapPanel.isContextMenuVisible()
}
```

**Review by tigrim — APPROVED** [review]
